import type { PropertyType, TenantType, PaymentType } from "./types";

export const mockProperties: PropertyType[] = [
  {
    id: "1",
    name: "Modern Downtown Apartment",
    location: "New York, NY",
    price: 750000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    type: "Apartment",
    status: "For Sale",
    description:
      "Luxurious apartment in the heart of downtown with stunning city views. Features include hardwood floors, stainless steel appliances, and a spacious balcony. Building amenities include a fitness center, rooftop pool, and 24-hour concierge service.",
    image:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    features: [
      "Hardwood Floors",
      "Stainless Steel Appliances",
      "Balcony",
      "Fitness Center",
      "Pool",
    ],
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    id: "2",
    name: "Suburban Family Home",
    location: "Austin, TX",
    price: 550000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2500,
    type: "House",
    status: "For Sale",
    description:
      "Spacious family home in a quiet suburban neighborhood. Features a large backyard, updated kitchen, and a two-car garage. Close to excellent schools, parks, and shopping centers.",
    image:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    features: [
      "Large Backyard",
      "Updated Kitchen",
      "Two-Car Garage",
      "Quiet Neighborhood",
      "Near Schools",
    ],
    latitude: 30.2672,
    longitude: -97.7431,
  },
  {
    id: "3",
    name: "Luxury Beachfront Condo",
    location: "Miami, FL",
    price: 1200000,
    bedrooms: 3,
    bathrooms: 3.5,
    sqft: 2200,
    type: "Condo",
    status: "For Sale",
    description:
      "Stunning beachfront condo with panoramic ocean views. Features include floor-to-ceiling windows, a gourmet kitchen, and a spacious master suite. Building amenities include a private beach, infinity pool, and full-service spa.",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    features: [
      "Ocean View",
      "Floor-to-Ceiling Windows",
      "Gourmet Kitchen",
      "Private Beach",
      "Infinity Pool",
    ],
    latitude: 25.7617,
    longitude: -80.1918,
  },
  {
    id: "4",
    name: "Urban Loft",
    location: "Chicago, IL",
    price: 425000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 950,
    type: "Apartment",
    status: "For Sale",
    description:
      "Stylish urban loft in a converted warehouse. Features exposed brick walls, high ceilings, and large windows. Located in a trendy neighborhood with easy access to restaurants, shops, and public transportation.",
    image:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    features: [
      "Exposed Brick",
      "High Ceilings",
      "Large Windows",
      "Trendy Neighborhood",
      "Public Transportation",
    ],
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: "5",
    name: "Mountain Retreat",
    location: "Denver, CO",
    price: 875000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3200,
    type: "House",
    status: "For Sale",
    description:
      "Beautiful mountain home with breathtaking views. Features a stone fireplace, gourmet kitchen, and a large deck. Perfect for outdoor enthusiasts with easy access to hiking, skiing, and mountain biking.",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    features: [
      "Mountain Views",
      "Stone Fireplace",
      "Gourmet Kitchen",
      "Large Deck",
      "Outdoor Activities",
    ],
    latitude: 39.7392,
    longitude: -104.9903,
  },
  {
    id: "6",
    name: "Cozy Townhouse",
    location: "Seattle, WA",
    price: 625000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1800,
    type: "Townhouse",
    status: "For Rent",
    description:
      "Modern townhouse in a desirable neighborhood. Features an open floor plan, updated kitchen, and a private patio. Close to parks, coffee shops, and tech campuses.",
    image:
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    features: [
      "Open Floor Plan",
      "Updated Kitchen",
      "Private Patio",
      "Near Parks",
      "Tech Hub",
    ],
    latitude: 47.6062,
    longitude: -122.3321,
  },
  {
    id: "7",
    name: "Historic Brownstone",
    location: "Boston, MA",
    price: 1500000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800,
    type: "Townhouse",
    status: "For Sale",
    description:
      "Beautifully restored historic brownstone with original architectural details. Features a gourmet kitchen, formal dining room, and a private garden. Located in a prestigious neighborhood with easy access to downtown.",
    image:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    features: [
      "Historic Details",
      "Gourmet Kitchen",
      "Formal Dining Room",
      "Private Garden",
      "Prestigious Location",
    ],
    latitude: 42.3601,
    longitude: -71.0589,
  },
  {
    id: "8",
    name: "Desert Oasis",
    location: "Phoenix, AZ",
    price: 700000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2600,
    type: "House",
    status: "For Rent",
    description:
      "Modern desert home with a resort-style backyard. Features include a pool, spa, and outdoor kitchen. Interior highlights include an open floor plan, high ceilings, and a gourmet kitchen.",
    image:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
    features: [
      "Pool",
      "Spa",
      "Outdoor Kitchen",
      "Open Floor Plan",
      "High Ceilings",
    ],
    latitude: 33.4484,
    longitude: -112.074,
  },
];

export const mockTenants: TenantType[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@example.com",
    phone: "(555) 123-4567",
    propertyId: "6",
    leaseStart: new Date("2023-01-01"),
    leaseEnd: new Date("2024-01-01"),
    rentAmount: 2500,
    paymentStatus: "Paid",
  },
  {
    id: "2",
    name: "Emily Johnson",
    email: "emily.johnson@example.com",
    phone: "(555) 987-6543",
    propertyId: "8",
    leaseStart: new Date("2023-03-15"),
    leaseEnd: new Date("2024-03-15"),
    rentAmount: 3200,
    paymentStatus: "Pending",
  },
  {
    id: "3",
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "(555) 456-7890",
    propertyId: "4",
    leaseStart: new Date("2023-05-01"),
    leaseEnd: new Date("2024-05-01"),
    rentAmount: 1800,
    paymentStatus: "Overdue",
  },
];

export const mockPayments: PaymentType[] = [
  {
    id: "1",
    tenantId: "1",
    amount: 2500,
    date: new Date("2023-12-01"),
    status: "Paid",
    method: "Bank Transfer",
  },
  {
    id: "2",
    tenantId: "1",
    amount: 2500,
    date: new Date("2023-11-01"),
    status: "Paid",
    method: "Bank Transfer",
  },
  {
    id: "3",
    tenantId: "2",
    amount: 3200,
    date: new Date("2023-12-15"),
    status: "Pending",
    method: "Credit Card",
  },
  {
    id: "4",
    tenantId: "2",
    amount: 3200,
    date: new Date("2023-11-15"),
    status: "Paid",
    method: "Credit Card",
  },
  {
    id: "5",
    tenantId: "3",
    amount: 1800,
    date: new Date("2023-12-01"),
    status: "Overdue",
    method: "Cash",
  },
  {
    id: "6",
    tenantId: "3",
    amount: 1800,
    date: new Date("2023-11-01"),
    status: "Paid",
    method: "Cash",
  },
];
